# Change these first
owner: Adomi-Delivery # Your GitHub organization or username, where this repository lives
repo: adomi-status # The name of this repository

sites:
  - name: Adomi Website (WWW)
    url: https://www.adomi.app
  - name: Adomi Website (@)
    url: https://adomi.app
  - name: Adomi QR (WWW)
    url: https://www.adomiqr.com
  - name: Adomi QR (@)
    url: https://adomiqr.com
  - name: Dashboard Admin
    url: https://admin.adomi.app
  - name: Dashboard Aliados
    url: https://aliados.adomi.app
  - name: Ordenes Web
    url: https://ordenes.adomi.app
  - name: Adomi Shop (@)
    url: https://adomi.shop
  - name: SOAT Shop (@)
    url: http://soat.shop
  - name: Openpay Sandbox
    url: https://sandbox-api.openpay.co
  - name: Adomi Core (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/core/api/v1
  - name: Adomi Orders (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/OrderMs
  - name: Adomi Environment (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/InitHandler/environment
  - name: Adomi Payment (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/payment    
  - name: Adomi Insurance (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/insurance
  - name: Adomi Wallet (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/wallet
  - name: Adomi Alerts (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/alerts/api/v1
  - name: Adomi Location (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/location/api/v1
  - name: Adomi Polygons (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/polygons/api/v1/city-polygons/by-city-id/c1e4bcc9-eb84-4653-872c-e38f8de4bf79
  - name: Adomi Reports (MS)
    url: https://us-central1-adomi-dev.cloudfunctions.net/reports/api/v1/reports/count-register-users

assignees:
  - daniel7byte

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /adomi-status
  logoUrl: https://adomi.app/assets/img/logo.png
  name: Adomi - Health Monitoring
  introTitle: "Adomi use **Upptime**, it's the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Adomi Servers](https://adomi.app/).
  navbar:
    - title: Status
      href: /adomi-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://adomi.app
    - title: Download
      href: https://adomiqr.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
